USE master
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'WHQJNativeWebDB')
DROP DATABASE [WHQJNativeWebDB]
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'WHQJPlatformManagerDB')
DROP DATABASE [WHQJPlatformManagerDB]
GO


/****** Object:  Database [WHQJNativeWebDB]    Script Date: 2017/7/13 17:49:26 ******/
CREATE DATABASE [WHQJNativeWebDB] ON  PRIMARY 
( NAME = N'WHQJNativeWebDB', FILENAME = N'D:\数据库\旗舰平台\WHQJNativeWebDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WHQJNativeWebDB_log', FILENAME = N'D:\数据库\旗舰平台\WHQJNativeWebDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WHQJNativeWebDB] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WHQJNativeWebDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [WHQJNativeWebDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WHQJNativeWebDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WHQJNativeWebDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WHQJNativeWebDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [WHQJNativeWebDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WHQJNativeWebDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET RECOVERY FULL 
GO

ALTER DATABASE [WHQJNativeWebDB] SET  MULTI_USER 
GO

ALTER DATABASE [WHQJNativeWebDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WHQJNativeWebDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WHQJNativeWebDB] SET  READ_WRITE 
GO

/****** Object:  Database [WHQJPlatformManagerDB]    Script Date: 2017/7/13 17:50:29 ******/
CREATE DATABASE [WHQJPlatformManagerDB] ON  PRIMARY 
( NAME = N'RY_WHQJPlatformManagerDB', FILENAME = N'D:\数据库\旗舰平台\WHQJPlatformManagerDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RY_WHQJPlatformManagerDB_log', FILENAME = N'D:\数据库\旗舰平台\WHQJPlatformManagerDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WHQJPlatformManagerDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET RECOVERY FULL 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET  MULTI_USER 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WHQJPlatformManagerDB] SET  READ_WRITE 
GO