USE [master]
GO

IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'WHQJAgentDB')
DROP DATABASE [WHQJAgentDB]
GO


/****** Object:  Database [WHQJAgentDB]    Script Date: 2018/4/13 9:26:56 ******/
CREATE DATABASE [WHQJAgentDB] ON  PRIMARY 
( NAME = N'WHQJAgentDB', FILENAME = N'D:\数据库\旗舰平台\WHQJAgentDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WHQJAgentDB_log', FILENAME = N'D:\数据库\旗舰平台\WHQJAgentDB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [WHQJAgentDB] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WHQJAgentDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [WHQJAgentDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [WHQJAgentDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WHQJAgentDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WHQJAgentDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [WHQJAgentDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WHQJAgentDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET RECOVERY FULL 
GO

ALTER DATABASE [WHQJAgentDB] SET  MULTI_USER 
GO

ALTER DATABASE [WHQJAgentDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WHQJAgentDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WHQJAgentDB] SET  READ_WRITE 
GO